// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// Location is the predicate function for location builders.
type Location func(*sql.Selector)

// Ticket is the predicate function for ticket builders.
type Ticket func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
